name: nix-proto-gen
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.11]
    steps:
        - uses: cachix/install-nix-action@v23
        - name: Get branch names
          id: branch-name
          uses: tj-actions/branch-names@v7
        - uses: actions/checkout@v4
          with:
            repository: RCMast3r/data_acq
            ref: refs/heads/master
        - run: nix develop .#ci --override-input nixpkgs github:NixOS/nixpkgs/release-${{ matrix.version}} --command ht_dbc_proto_creator.py
        
        - name: Get current date and time
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"

        # - name: release
        #   uses: actions/create-release@v1
        #   id: create_release
        #   with:
        #     draft: false
        #     prerelease: false
        #     body: |
        #       - dbc and proto release
        #     release_name: yo
        #     tag_name: ${{ steps.date.outputs.date }}
        #     owner: RCMast3r
        #     # repo: hytech_dbc_proto
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ steps.date.outputs.date }} 
            files: hytech.dbc